apiVersion: apps/v1
kind: Deployment
metadata:
  name: settelmint-deployment
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: app-container
        image: settelmintacr.azurecr.io/devops-assignment:latest
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: settelmint-service
spec:
  type: LoadBalancer
  selector:
    app: node-app
  ports:
  - port: 8080
    targetPort: 3001
    protocol: TCP
