name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - uses: actions/setup-node@v3
        with:
            node-version: 18
      - name: NPM Install
        run: |
         npm install --global nx@latest

      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.2.0
        with:
          host: http://192.168.1.101:9000
          login: sqa_05128c57a4ee76768eedf331f593ea8f47679103
          projectName: settelmint-assignment
            
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci

  #    - run: yarn nx run-many --target=build --all 
      
    #  - run: npx nx run nft-bridge:lint
      - run: npx create-nx-workspace

   #   - run: npx jest
   #     working-directory: ./apps/nft-bridge-e2e
      - run: nx build nft-bridge
      - run: |
            ls -a
            pwd
      
