name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - uses: actions/setup-node@v3
        with:
            node-version: 18
      - name: NPM Install
        run: |
         npm install --global nx@latest
            
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci

  #    - run: yarn nx run-many --target=build --all 
      
    #  - run: npx nx run nft-bridge:lint
      - run: npx create-nx-workspace

   #   - run: npx jest
   #     working-directory: ./apps/nft-bridge-e2e
      - run: nx build nft-bridge
      - run: |
            ls -a
            pwd
      
