name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - uses: actions/setup-node@v3
        with:
            node-version: 18
      - name: NPM Install
        run: |
         npm install --global nx@latest

  #    - name: SonarQube Scan
  #      uses: kitabisa/sonarqube-action@v1.2.0
  #      with:
  #        host: 'http://20.55.236.109:9000'
  #        login: 'sqa_69535048f60e432603acb217d4aa5b915a7c2c3c'
  #        projectName: settelmint-assignment
            
      - name: Install NPM CI
        run: npm ci

      - name: Check Linting
        run: npx nx run nft-bridge:lint

      - name: Allow port
        run: |
          sudo ufw allow 3000
          sudo ufw status
          sudo ufw enable

      - name: Unit Test
        run: npx jest
        continue-on-error: true
        
      - name: Build
        run: nx build nft-bridge

      - name: Get main.ts
        run: |
         cat dist/apps/nft-bridge/main.js
         
      - name: Build Docker image
        run: |
          docker build -t test .
          
