name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - uses: actions/setup-node@v3
        with:
            node-version: 18
      - name: NPM Install
        run: |
         npm install
            
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      
      - run: npx nx run nft-bridge:lint

      #- run: npx jest
      - run: nx build nft-bridge
        working-directory: ./apps/nft-bridge/
